version: '3.9'

networks: 
    tig-network:
        driver: bridge

volumes:
    influxdb-data:
    grafana-data:

services:
    influxdb:
        container_name: influxdb
        image: influxdb:latest
        ports: 
            - 8086:8086 
        networks:
            - tig-network 
        volumes:
            - influxdb-data:/var/lib/influxdb
        restart: always

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        ports: 
            - 3000:3000
        environment:
            GF_SECURITY_ADMIN_USER: grafadmin
            GF_SECURITY_ADMIN_PASSWORD: grafpw
        networks: 
            - tig-network
        volumes:
            - grafana-data:/var/lib/grafana
        restart: always        

    telegraf:
        image: telegraf:latest
        depends_on: 
            - "influxdb"
        environment:
            HOST_NAME: "telegraf"
            INFLUXDB_HOST: "influxdb"
            INFLUXDB_PORT: "8086"
            DATABASE: "iot"
        volumes:
            - ./telegraf.conf:/etc/telegraf/telegraf.conf
        tty: true
        networks: 
            - tig-network
        privileged: true
        restart: always
